### ISSUE TITLE
安装时一直报错

### ISSUE THREAD

**Issue by piaoluoya** [orzcc/aliyun-oss#1]
先是在lavarel5.0环境中安装
其中部分配置：
        "minimum-stability": "dev",
    "require": {
        "laravel/framework": "5.0.*",
        "orzcc/aliyun-oss": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "orzcc/aliyun-oss": "dev-master"
    },

报错：
Please provide a version constraint for the orzcc/aliyun-oss requirement: dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package orzcc/aliyun-oss could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

参考下面这个网页上的方法，我单独出来下载还是报一样的错：
http://stackoverflow.com/questions/23083045/the-package-is-not-available-in-a-stable-enough-version-according-to-your-minimu

单独安装时的配置如下：
{
    "name":"orzcc/aliyun-oss",
    "minimum-stability": "dev",
    "require": {
        "orzcc/aliyun-oss": "dev-master"
    }  
}

**Comment by orzcc** [comment]
你先用命令来新增包（注意先把你composer.json更新过的恢复好）：
composer require orzcc/aliyun-oss dev-master

当前这个版本不是稳定版本，但我自己项目中已经在使用了。版本号暂时还没加，后期有空了会考虑加上~

**Comment by piaoluoya** [comment]
谢谢你回复。
问题解决了。是我的问题，原来是因为我用的composer的中国镜像，应该是中国镜像中没有这个package
