### ISSUE TITLE
move()方法的参数是否不支持带目录的形式？

### ISSUE THREAD

**Issue by DinicChen** [orzcc/aliyun-oss#8]
``` php
Storage::disk('oss')->move('test/test1.png', 'img/a.png');
```

会报错：

> FatalErrorException in AliyunOssAdapter.php line 357:
> Call to a member function getTimestamp() on null

**Comment by DinicChen** [comment]
我发现是有时候可以，有时候不可以，成功率很低。是否阿里云问题？

**Comment by orzcc** [comment]
move方式adapter 调用的就是 rename 方法，阿里云没有move 或 rename 方法，所以用以下伪 rename 实现（拷贝+删除旧的），不知道是不是这个原因造成偶发性操作失败。

另外，Call to a member function getTimestamp() on null 这个报错的确是个 bug，已修正~

**Comment by orzcc** [comment]
move方式adapter 调用的就是 rename 方法，阿里云没有move 或 rename 方法，所以用以下伪 rename 实现（拷贝+删除旧的），不知道是不是这个原因造成偶发性操作失败。

另外，Call to a member function getTimestamp() on null 这个报错的确是个 bug，已修正~
