### ISSUE TITLE
是发布的有问题么？为什么安装不成功

### ISSUE THREAD

**Issue by dolia** [orzcc/aliyun-oss#9]
composer require orzcc/aliyun-oss

 [InvalidArgumentException]  
  Could not find package orzcc/aliyun-oss at any version for your minimum-sta  
  bility (stable). Check the package spelling or your minimum-stability

**Comment by orzcc** [comment]
使用这个来代替吧，现在没有加版本号，到时有时间再来加。

composer require orzcc/aliyun-oss dev-master
